version: "3.7"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    build:
      context: .
      args:
        - PIHOLE_VERSION
    image: pihole_unbound
    container_name: pihole_unbound
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    cpus: 0.5
    mem_limit: 512M
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp
    environment:
      WEBPASSWORD: ${WEBPASSWORD}
      TZ: ${TZ}
      # PROXY_LOCATION: pihole
      PIHOLE_DNS_: 127.0.0.1#5335
      FTLCONF_CHECK_DISK: 0 # For MacOS https://github.com/pi-hole/docker-pi-hole/issues/951
      DNSSEC: "true"
      DNSMASQ_LISTENING: single
      # FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      # REV_SERVER: ${REV_SERVER:-false}
      # REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      # REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      # REV_SERVER_CIDR: ${REV_SERVER_CIDR}
    # Volumes store your data between container upgrades
    volumes:
      - ./etc/pihole:/etc/pihole
      # - ./etc/dnsmasq.d/:/etc/dnsmasq.d
      - ./etc/dnsmasq.d/99-edns.conf:/etc/dnsmasq.d/99-edns.conf
      - ./etc/unbound/unbound.conf.d/pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf
      - ./log/:/var/log/
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
